# Generated by Django 5.2.14 on 2026-05-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbspy', '0017_alter_gamelog_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['ingame_id', 'game'], name='pbspy_player_ingame_game_idx'),
        ),
    ]
